#!/usr/bin/env python3
"""One-off B2-D reviewed-set builder (run by the batch author, then frozen).

Assembles reviewed questions over B2-C fixture cases, runs the answer
pipeline, and writes tests/fixtures/b2d_answer_set.json with GENERATED
outputs recorded. The author then reads every answer (human verification,
§18) and freezes expected verdicts; tests assert exact equality afterwards.
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO / "backend"))
sys.path.insert(0, str(REPO / "ingest/judgements"))

from app import b2d_answer as A  # noqa: E402
from app import b2c_evidence as E  # noqa: E402
from app import b2b_cite as C  # noqa: E402
from app import b1_serve as B1  # noqa: E402

B2C = json.loads((REPO / "tests/fixtures/b2c_reasoning_set.json").read_text(encoding="utf-8"))
CASES = {c["case_id"]: c for c in B2C["cases"]}
corpus = B1.StatuteCorpus.from_jsonl()

QUESTIONS = [
    {"qid": "A-01-demo-dismissal",
     "question": "原告依民法第184條第1項及第195條第1項前段請求被告賠償非財產上損害新臺幣3萬元，法院准許了嗎？理由為何？",
     "b2c_cases": ["R-06-demo-disposition", "R-07-demo-holding"],
     "require_statutes": False, "jdate": "20260713"},
    {"qid": "A-02-detention-cause",
     "question": "受收容人CHIN CHENG KIT本次續予收容的「具收容事由」勾選了哪一項？",
     "b2c_cases": ["R-04-detention-full-doc"],
     "require_statutes": False, "jdate": "20260710"},
    {"qid": "A-03-violence-why",
     "question": "被告傷害告訴人的行為，為何構成家庭暴力罪？",
     "b2c_cases": ["R-02-home-violence-reasoning"],
     "require_statutes": False, "jdate": "20260730"},
    {"qid": "A-04-payment-require-statutes",
     "question": "這份支付命令的依據為何？",
     "b2c_cases": ["R-03-payment-order-flagged"],
     "require_statutes": True, "jdate": "20260713"},
]


def build_answer_for(spec):
    chunks, jid = [], None
    for cid in spec["b2c_cases"]:
        for ch in CASES[cid]["chunks"]:
            chunks.append(ch)
            jid = ch["document_id"]
    cites = []
    for ch in chunks:
        cites.extend(C.extract_citations(
            ch["text"], jid=ch["document_id"], chunk_index=ch["chunk_index"],
            corpus=corpus))
    graph = E.build_evidence_graph(chunks, cites)
    evs = [c["statute_evidence"] for c in cites if c["statute_evidence"]]
    return A.build_answer(spec["question"], judgement_id=jid, graph=graph,
                          citations=cites, statute_evidences=evs,
                          require_statutes=spec["require_statutes"],
                          jdate=spec.get("jdate", ""))


out = {"verification_status": "AUTHOR_REVIEWED",
       "provenance": "reviewed questions over frozen B2-C cases; answers generated by the pipeline under review",
       "questions": []}
for spec in QUESTIONS:
    r = build_answer_for(spec)
    out["questions"].append({**{k: spec[k] for k in ("qid", "question", "b2c_cases",
                                                    "require_statutes")},
                             "response": r})
p = REPO / "tests/fixtures/b2d_answer_set.json"
p.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
for q in out["questions"]:
    r = q["response"]
    print("=" * 30, q["qid"], r["status"],
          (r.get("abstention") or {}).get("reason", ""),
          f"{len(r['claims'])} claims")
print(f"wrote {p} — HUMAN REVIEW (§18) REQUIRED BEFORE FREEZING")
