#!/usr/bin/env python3
"""One-off B4-B reviewed-set builder (run by the batch author, then frozen).

Assembles reviewed multi-evidence answers from real B2-C fixture cases via
the real pipeline (B2-C graph + B2-B citations + sectioned composer). The
author reads every generated answer in full (human verification) before
freezing; tests assert exact equality afterwards. Re-running overwrites
(review required again).
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO / "backend"))
sys.path.insert(0, str(REPO / "ingest/judgements"))

from app import b4b_compose as B4  # noqa: E402
from app import b2c_evidence as E  # noqa: E402
from app import b2b_cite as C  # noqa: E402
from app import b1_serve as B1  # noqa: E402

B2C = {c["case_id"]: c for c in
       json.loads((REPO / "tests/fixtures/b2c_reasoning_set.json").read_text(encoding="utf-8"))["cases"]}
CORPUS = B1.StatuteCorpus.from_jsonl()

QUESTIONS = [
    {"qid": "M-01-demo-dismissal",
     "question": "原告依民法第184條第1項及第195條第1項前段請求被告賠償非財產上損害新臺幣3萬元，法院准許了嗎？理由為何？",
     "b2c_cases": ["R-06-demo-disposition", "R-07-demo-holding"],
     "kwargs": {"jdate": "20260713"}},
    {"qid": "M-02-detention-cause",
     "question": "受收容人CHIN CHENG KIT本次續予收容的「具收容事由」勾選了哪一項？",
     "b2c_cases": ["R-04-detention-full-doc"],
     "kwargs": {"jdate": "20260710"}},
    {"qid": "M-03-demo-partial",
     "question": "原告之訴結果為何？法院的理由為何？",
     "b2c_cases": ["R-06-demo-disposition", "R-07-demo-holding"],
     "kwargs": {"jdate": "20260713",
                "sections": ["DISPOSITION", "HOLDING", "REASONING"]}},
    {"qid": "M-04-reasoning-only-abstain",
     "question": "被告為何構成犯罪？",
     "b2c_cases": ["R-02-home-violence-reasoning"],
     "kwargs": {}},
    {"qid": "M-05-payment-order-abstain",
     "question": "這份支付命令的依據為何？",
     "b2c_cases": ["R-03-payment-order-flagged"],
     "kwargs": {}},
]


def build_for(spec):
    chunks, jid = [], None
    for cid in spec["b2c_cases"]:
        for ch in B2C[cid]["chunks"]:
            chunks.append(ch)
            jid = ch["document_id"]
    cites = []
    for ch in chunks:
        cites.extend(C.extract_citations(
            ch["text"], jid=ch["document_id"], chunk_index=ch["chunk_index"],
            corpus=CORPUS))
    graph = E.build_evidence_graph(chunks, cites)
    evs = [c["statute_evidence"] for c in cites if c["statute_evidence"]]
    return B4.compose_sectioned(spec["question"], judgement_id=jid,
                                graph=graph, citations=cites,
                                statute_evidences=evs, **spec["kwargs"])


out = {"verification_status": "AUTHOR_REVIEWED",
       "provenance": "reviewed multi-evidence answers over frozen B2-C cases; generated by the pipeline under review",
       "questions": []}
for spec in QUESTIONS:
    r = build_for(spec)
    out["questions"].append({**{k: spec[k] for k in ("qid", "question", "b2c_cases")},
                             "kwargs": spec["kwargs"],
                             "response": r})
p = REPO / "tests/fixtures/b4b_answer_eval.json"
p.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
for q in out["questions"]:
    r = q["response"]
    print("=" * 30, q["qid"], r["status"],
          (r.get("abstention") or {}).get("reason", ""),
          f"{len(r['claims'])} claims",
          f"{len(r.get('sections', []))} sections")
print(f"wrote {p} — HUMAN REVIEW REQUIRED BEFORE FREEZING")
